### ISSUE TITLE
Do you have any detailed documentation?

### ISSUE THREAD

**Issue by faphdev** [Zimbra/zinstaller#2]
Looks like this is intended for someone who already knows how to use it as there is no explanation or documentation.

**Comment by ghost** [comment]
https://wiki.zimbra.com/wiki/Cipher_suites
https://wiki.zimbra.com/wiki/Secopstips
https://zimbra.github.io/zimbra-9/adminguide.html

**Comment by ghost** [comment]
https://wiki.zimbra.com/wiki/DNS
